### ISSUE TITLE
iOS 13 - layout issue when view is presented initially .half

### ISSUE THREAD

**Issue by Tbruni85** [SCENEE/FloatingPanel#278]
### Short description
Hi,
On iOS 13 we noticed a weird behaviour. We use the floating panel to display a table with some options. The view is initially presented in .half mode. 
On iOS 13 the layout is broken and the floating panel doesn't get the bounds of the child.
This issues disappears when the panel is open and then closed back.

### Expected behavior
The panel should get the child view bounds correctly.

### Actual behavior
![Screenshot 2019-10-22 at 12 16 25](https://user-images.githubusercontent.com/13588914/67280795-da513300-f4c5-11e9-90d5-ac02321ab5db.png)

### Steps to reproduce
We set up the panel like this:
```
private func setupQuoteListPanel() {
        let mainPanelVC = FloatingPanelController()
        mainPanelVC.delegate = self
        mainPanelVC.isRemovalInteractionEnabled = false
        mainPanelVC.surfaceView.shadowHidden = false
        mainPanelVC.surfaceView.backgroundColor = .clear
        mainPanelVC.set(contentViewController: quoteListView)
        mainPanelVC.track(scrollView: quoteListView.tableView)
        setupGrabberHandle(forVC: mainPanelVC)
        quoteListPanelVC = mainPanelVC
    }
```
The only way we found to fix the issue is forcing the panel to go full and then back to half without animation:

```
        quoteListPanelVC?.move(to: .full, animated: false)
        quoteListPanelVC?.move(to: .half, animated: false)
```

### Environment
Xcode 11.1
iOS 13.1

**Comment by SCENEE** [comment]
Does this problem occur on v1.7.0? I encountered the same problem on v1.3.x or v1.4.x and then I fixed it. If on v1.7.0, I would like you to capture an screen capture of visual debugging because the issue looks caused by an invalid `FloatingPanelSurfaceView.containerView` layout because the content view is wrapped incorrectly.

**Comment by Tbruni85** [comment]
Sorry for the late reply, 
Just noticed the issue is still present on both iOS 12 and 13, please see screenshot attached.
Now even forcing the panel to full and back to half solves the issue.

Please see screenshot attached

![Simulator Screen Shot - iPhone 8 Plus - 2019-11-21 at 10 41 31](https://user-images.githubusercontent.com/13588914/69330794-8617ab00-0c4b-11ea-9d11-5c15d61b4ada.png)

Layout hierarchy:
<img width="816" alt="Screenshot 2019-11-21 at 10 48 35" src="https://user-images.githubusercontent.com/13588914/69331388-91b7a180-0c4c-11ea-9798-f17a9d76c7fd.png">


As you can see the table is displayed correctly.
Hope this helps

**Comment by Tbruni85** [comment]
Hi
I dug more into the issue and I realised the problem was mostly on my side. 
The loading view used before showing the table wasn't laid out correctly resulting in a truncated view.
Not sure if you designed the component to adapt its view based on the intrinsic contents size of the child view or if the content view should equal the leading and trailing of its superview.

I'm closing the issue, thank you for your help

**Comment by SCENEE** [comment]
> Not sure if you designed the component to adapt its view based on the intrinsic contents size of the child view or if the content view should equal the leading and trailing of its superview.

The component supports both of them. `FloatingPanelLayout` is for the later, but you can use `FloatingPanelIntrinsicLayout` for the former use case.
